/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "on-tertiary-container": "#1c2c40",
              "surface-container-low": "#fff0ef",
              "on-secondary-fixed": "#191c20",
              "on-secondary-fixed-variant": "#44474b",
              "secondary-container": "#e1e2e8",
              "error-container": "#ffdad6",
              "on-error": "#ffffff",
              "on-secondary-container": "#626469",
              "outline-variant": "#e1bebc",
              "on-tertiary-fixed": "#0b1c30",
              "inverse-on-surface": "#ffedeb",
              "surface-variant": "#f6dddb",
              "on-background": "#261817",
              "on-primary-container": "#5e000d",
              "on-primary-fixed-variant": "#900c1d",
              "secondary-fixed": "#e1e2e8",
              "surface-container": "#ffe9e7",
              "on-primary": "#ffffff",
              "background": "#fff8f7",
              "tertiary-container": "#8393ab",
              "error": "#ba1a1a",
              "primary": "#f43f5e",
              "surface-container-lowest": "#ffffff",
              "surface-container-highest": "#f6dddb",
              "tertiary-fixed-dim": "#b7c8e1",
              "surface-dim": "#eed4d3",
              "surface-container-high": "#fce2e1",
              "surface-bright": "#fff8f7",
              "secondary-fixed-dim": "#c5c6cc",
              "inverse-primary": "#ffb3b0",
              "inverse-surface": "#3c2d2c",
              "on-error-container": "#93000a",
              "tertiary": "#505f76",
              "tertiary-fixed": "#d3e4fe",
              "on-secondary": "#ffffff",
              "surface-tint": "#e84750",
              "on-surface-variant": "#59413f",
              "on-tertiary-fixed-variant": "#38485d",
              "surface": "#fff8f7",
              "primary-fixed": "#ffdad8",
              "primary-fixed-dim": "#ffb3b0",
              "on-surface": "#261817",
              "primary-container": "#f85d5f",
              "on-tertiary": "#ffffff",
              "on-primary-fixed": "#410006",
              "secondary": "#5c5e63",
              "outline": "#8d706f"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "gutter": "24px",
              "lg": "48px",
              "base": "8px",
              "md": "24px",
              "sm": "12px",
              "xs": "4px",
              "xl": "80px",
              "container-max": "1280px"
      },
      "fontFamily": {
              "headline-md": ["Plus Jakarta Sans"],
              "label-sm": ["Plus Jakarta Sans"],
              "headline-lg-mobile": ["Plus Jakarta Sans"],
              "label-md": ["Plus Jakarta Sans"],
              "display-lg": ["Plus Jakarta Sans"],
              "body-lg": ["Plus Jakarta Sans"],
              "body-md": ["Plus Jakarta Sans"],
              "headline-lg": ["Plus Jakarta Sans"],
              "sans": ["Plus Jakarta Sans", "sans-serif"]
      },
      "fontSize": {
              "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
              "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}],
              "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "700"}],
              "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600"}],
              "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
              "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
              "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
